services:
  spark:
    build: .
    container_name: spark
    ports:
      - "4040:4040"  
      - "8080:8080"  
    volumes:
      - ./data:/BD_lab_3/data
      - ./data/train.csv:/BD_lab_3/data/train.csv 
      - ./src:/BD_lab_3/src
      - ./logs:/BD_lab_3/logs
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - SPARK_HOME=/opt/bitnami/spark
      - SPARK_DRIVER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=1g
    networks:
      - spark-net
    deploy:
          resources:
            limits:
              memory: 2G
networks:
  spark-net:
    driver: bridge